name: Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Create firebase_options.dart
      run: |
        /bin/mkdir -p lib
        echo "${{ secrets.FIREBASE_OPTIONS_DART }}" > lib/firebase_options.dart

    - name: Enable Flutter web
      run: flutter config --enable-web

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web

    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "build/web/" # Otimizado para copiar todo o conteúdo
        target: ${{ secrets.PATH }}

    - name: Restart web server (opcional)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl restart nginx
