name: Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Enable Flutter web
      run: flutter config --enable-web
      shell: sh

    - name: Install dependencies
      run: flutter pub get

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Install FlutterFire CLI
      run: dart pub global activate flutterfire_cli

    - name: Configure FlutterFire
      run: |
        flutterfire configure --project=SEU_ID_DO_PROJETO_FIREBASE \
        --out=lib/firebase_options.dart \
        --yes \
        --platforms=android,ios,web # Especifique as plataformas desejadas
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: Build Flutter Web
      run: flutter build web

    - name: Deploy via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "build/web/*"
        target: ${{ secrets.PATH }}

    - name: Restart web server (opcional)
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl restart nginx
